import '../models/payment_status.dart';
import '../models/portfolio_snapshot.dart';
import '../models/property_models.dart';

class SeedData {
  SeedData._();

  static final PortfolioSnapshot snapshot = PortfolioSnapshot(
    properties: const [
      RentalProperty(
        id: 'emerald-heights',
        name: 'Emerald Heights',
        address: '4278 Maplewood Avenue, Lakeside District, Kathmandu',
        totalRooms: 12,
        occupiedRooms: 10,
        monthlyTarget: 14500,
        totalDue: 2150,
        rooms: [
          Room(
            id: 'r-101',
            propertyId: 'emerald-heights',
            label: '101',
            tenantName: 'Jane Cooper',
            dueDay: 5,
            monthlyRent: 1280,
            status: PaymentStatus.paid,
            note: 'Paid on time',
          ),
          Room(
            id: 'r-102',
            propertyId: 'emerald-heights',
            label: '102',
            tenantName: 'Robert Fox',
            dueDay: 1,
            monthlyRent: 1325,
            status: PaymentStatus.due,
            note: 'Reminder sent yesterday',
          ),
          Room(
            id: 'r-201',
            propertyId: 'emerald-heights',
            label: '201',
            tenantName: 'Cody Fisher',
            dueDay: 10,
            monthlyRent: 1190,
            status: PaymentStatus.paid,
            note: 'Utilities cleared',
          ),
          Room(
            id: 'r-202',
            propertyId: 'emerald-heights',
            label: '202',
            tenantName: 'Esther Howard',
            dueDay: 2,
            monthlyRent: 1210,
            status: PaymentStatus.due,
            note: 'Rent due this week',
          ),
        ],
      ),
      RentalProperty(
        id: 'maple-court',
        name: 'Maple Court',
        address: 'Pulchowk Road, Lalitpur',
        totalRooms: 8,
        occupiedRooms: 7,
        monthlyTarget: 9800,
        totalDue: 860,
        rooms: [
          Room(
            id: 'm-301',
            propertyId: 'maple-court',
            label: '301',
            tenantName: 'Marvin McKinney',
            dueDay: 4,
            monthlyRent: 1160,
            status: PaymentStatus.paid,
            note: 'All bills collected',
          ),
          Room(
            id: 'm-302',
            propertyId: 'maple-court',
            label: '302',
            tenantName: 'Kristin Watson',
            dueDay: 7,
            monthlyRent: 1110,
            status: PaymentStatus.partial,
            note: 'Internet pending',
          ),
        ],
      ),
      RentalProperty(
        id: 'riverside-nest',
        name: 'Riverside Nest',
        address: 'Boudha Circle, Kathmandu',
        totalRooms: 10,
        occupiedRooms: 9,
        monthlyTarget: 12100,
        totalDue: 1280,
        rooms: [
          Room(
            id: 'rs-401',
            propertyId: 'riverside-nest',
            label: '401',
            tenantName: 'Savannah Nguyen',
            dueDay: 3,
            monthlyRent: 1235,
            status: PaymentStatus.paid,
            note: 'Paid with electricity',
          ),
          Room(
            id: 'rs-402',
            propertyId: 'riverside-nest',
            label: '402',
            tenantName: 'Devon Lane',
            dueDay: 8,
            monthlyRent: 1185,
            status: PaymentStatus.paid,
            note: 'No dues',
          ),
        ],
      ),
    ],
    tenants: [
      TenantProfile(
        id: 't-jane',
        roomId: 'r-101',
        propertyId: 'emerald-heights',
        name: 'Jane Cooper',
        phone: '+977-9801001001',
        moveInDate: DateTime(2024, 2, 10),
        emergencyContact: 'M. Cooper (+977-9811001001)',
      ),
      TenantProfile(
        id: 't-robert',
        roomId: 'r-102',
        propertyId: 'emerald-heights',
        name: 'Robert Fox',
        phone: '+977-9801001002',
        moveInDate: DateTime(2023, 9, 18),
        emergencyContact: 'D. Fox (+977-9811001002)',
      ),
      TenantProfile(
        id: 't-cody',
        roomId: 'r-201',
        propertyId: 'emerald-heights',
        name: 'Cody Fisher',
        phone: '+977-9801001003',
        moveInDate: DateTime(2024, 1, 6),
        emergencyContact: 'R. Fisher (+977-9811001003)',
      ),
      TenantProfile(
        id: 't-esther',
        roomId: 'r-202',
        propertyId: 'emerald-heights',
        name: 'Esther Howard',
        phone: '+977-9801001004',
        moveInDate: DateTime(2025, 3, 2),
        emergencyContact: 'S. Howard (+977-9811001004)',
      ),
      TenantProfile(
        id: 't-marvin',
        roomId: 'm-301',
        propertyId: 'maple-court',
        name: 'Marvin McKinney',
        phone: '+977-9801001005',
        moveInDate: DateTime(2023, 8, 22),
        emergencyContact: 'K. McKinney (+977-9811001005)',
      ),
      TenantProfile(
        id: 't-kristin',
        roomId: 'm-302',
        propertyId: 'maple-court',
        name: 'Kristin Watson',
        phone: '+977-9801001006',
        moveInDate: DateTime(2024, 6, 15),
        emergencyContact: 'L. Watson (+977-9811001006)',
      ),
    ],
    revenue: const [
      MonthlyRevenuePoint(month: 'JAN', amount: 34200),
      MonthlyRevenuePoint(month: 'FEB', amount: 36750),
      MonthlyRevenuePoint(month: 'MAR', amount: 35840),
      MonthlyRevenuePoint(month: 'APR', amount: 42850),
      MonthlyRevenuePoint(month: 'MAY', amount: 40120),
      MonthlyRevenuePoint(month: 'JUN', amount: 41780),
    ],
    utilityUsage: const [
      UtilityUsage(
        propertyName: 'Skyline Residences',
        electricity: 2680,
        water: 740,
      ),
      UtilityUsage(
        propertyName: 'Oakwood Apartments',
        electricity: 1710,
        water: 470,
      ),
      UtilityUsage(
        propertyName: 'The Grand Manor',
        electricity: 3920,
        water: 980,
      ),
    ],
    utilityRecords: [
      UtilityRecord(
        id: 'u-1',
        propertyId: 'emerald-heights',
        propertyName: 'Emerald Heights',
        roomId: 'r-102',
        roomLabel: '102',
        tenantName: 'Robert Fox',
        type: UtilityType.electricity,
        meterReading: 422.1,
        amount: 1350,
        note: 'Late evening spike this month',
        imagePath: null,
        recordedAt: DateTime(2026, 5, 13, 18, 20),
      ),
      UtilityRecord(
        id: 'u-2',
        propertyId: 'maple-court',
        propertyName: 'Maple Court',
        roomId: 'm-302',
        roomLabel: '302',
        tenantName: 'Kristin Watson',
        type: UtilityType.internet,
        meterReading: null,
        amount: 1800,
        note: 'Shared 120 Mbps plan',
        imagePath: null,
        recordedAt: DateTime(2026, 5, 9, 9, 30),
      ),
      UtilityRecord(
        id: 'u-3',
        propertyId: 'riverside-nest',
        propertyName: 'Riverside Nest',
        roomId: 'rs-401',
        roomLabel: '401',
        tenantName: 'Savannah Nguyen',
        type: UtilityType.water,
        meterReading: 96.4,
        amount: 420,
        note: 'Normal month',
        imagePath: null,
        recordedAt: DateTime(2026, 5, 8, 16, 55),
      ),
    ],
    documents: [
      DocumentRecord(
        id: 'd-1',
        propertyId: 'emerald-heights',
        propertyName: 'Emerald Heights',
        roomId: 'r-101',
        roomLabel: '101',
        title: 'Lease Agreement - Jane Cooper',
        category: 'Lease',
        filePath: '/local/docs/lease_jane_cooper.pdf',
        note: 'Signed and verified',
        createdAt: DateTime(2026, 4, 28, 14, 10),
      ),
      DocumentRecord(
        id: 'd-2',
        propertyId: 'maple-court',
        propertyName: 'Maple Court',
        roomId: 'm-302',
        roomLabel: '302',
        title: 'Citizenship Copy - Kristin Watson',
        category: 'Identity',
        filePath: '/local/docs/id_kristin_watson.jpg',
        note: 'Scanned from camera',
        createdAt: DateTime(2026, 5, 2, 11, 45),
      ),
    ],
    activities: [
      ActivityEntry(
        id: 'a-1',
        propertyId: 'emerald-heights',
        title: 'Utility reading captured',
        detail: 'Room 102 electricity reading recorded with notes.',
        createdAt: DateTime(2026, 5, 13, 18, 22),
      ),
      ActivityEntry(
        id: 'a-2',
        propertyId: 'emerald-heights',
        title: 'Document archived',
        detail: 'Lease agreement for Jane Cooper added to local vault.',
        createdAt: DateTime(2026, 4, 28, 14, 12),
      ),
      ActivityEntry(
        id: 'a-3',
        propertyId: 'maple-court',
        title: 'Payment reminder sent',
        detail: 'Reminder queued for room 302 pending internet dues.',
        createdAt: DateTime(2026, 5, 10, 10, 30),
      ),
    ],
    pendingReceivables: const [
      PaymentReceivable(
        id: 'due-suite-401',
        propertyId: 'emerald-heights',
        propertyName: 'Emerald Heights',
        roomId: 'r-102',
        roomLabel: 'Suite 401',
        amount: 28500,
        overdueLabel: '14 days overdue',
        tags: ['Rent (2 months)', 'Internet (1 month)', 'Electricity'],
        status: PaymentStatus.due,
      ),
      PaymentReceivable(
        id: 'due-flat-202',
        propertyId: 'maple-court',
        propertyName: 'Maple Court',
        roomId: 'm-302',
        roomLabel: 'Flat 202',
        amount: 12200,
        overdueLabel: '3 days overdue',
        tags: ['Rent (1 month)', 'Maintenance'],
        status: PaymentStatus.due,
      ),
      PaymentReceivable(
        id: 'due-studio-b',
        propertyId: 'riverside-nest',
        propertyName: 'Riverside Nest',
        roomId: 'rs-401',
        roomLabel: 'Studio B',
        amount: 3450,
        overdueLabel: 'Since May 01',
        tags: ['Electricity', 'Water Tax'],
        status: PaymentStatus.partial,
      ),
    ],
    completedReceivables: const [
      PaymentReceivable(
        id: 'paid-suite-305',
        propertyId: 'emerald-heights',
        propertyName: 'Emerald Heights',
        roomId: 'r-101',
        roomLabel: 'Suite 305',
        amount: 15400,
        overdueLabel: 'Collected on May 12',
        tags: ['Rent', 'Water', 'Internet'],
        status: PaymentStatus.paid,
      ),
      PaymentReceivable(
        id: 'paid-loft-12',
        propertyId: 'riverside-nest',
        propertyName: 'Riverside Nest',
        roomId: 'rs-402',
        roomLabel: 'Loft 12',
        amount: 11200,
        overdueLabel: 'Collected on May 09',
        tags: ['Rent', 'Electricity'],
        status: PaymentStatus.paid,
      ),
    ],
    preferences: const AppPreferences(
      currencyCode: 'NPR',
      reminderDay: 5,
      landlordName: 'Aarav',
    ),
  );
}
