import '../models/payment_status.dart';
import '../models/portfolio_snapshot.dart';
import '../models/property_models.dart';

class SeedData {
  SeedData._();

  static final PortfolioSnapshot snapshot = PortfolioSnapshot(
    properties: const [
      RentalProperty(
        id: 'emerald-heights',
        name: 'Emerald Heights',
        address: '4278 Maplewood Avenue, Lakeside District, Kathmandu',
        totalRooms: 12,
        occupiedRooms: 10,
        monthlyTarget: 14500,
        totalDue: 2150,
        rooms: [
          Room(
            id: 'r-101',
            propertyId: 'emerald-heights',
            label: '101',
            tenantName: 'Jane Cooper',
            dueDay: 5,
            monthlyRent: 1280,
            status: PaymentStatus.paid,
            note: 'Paid on time',
          ),
          Room(
            id: 'r-102',
            propertyId: 'emerald-heights',
            label: '102',
            tenantName: 'Robert Fox',
            dueDay: 1,
            monthlyRent: 1325,
            status: PaymentStatus.due,
            note: 'Reminder sent yesterday',
          ),
          Room(
            id: 'r-201',
            propertyId: 'emerald-heights',
            label: '201',
            tenantName: 'Cody Fisher',
            dueDay: 10,
            monthlyRent: 1190,
            status: PaymentStatus.paid,
            note: 'Utilities cleared',
          ),
          Room(
            id: 'r-202',
            propertyId: 'emerald-heights',
            label: '202',
            tenantName: 'Esther Howard',
            dueDay: 2,
            monthlyRent: 1210,
            status: PaymentStatus.due,
            note: 'Rent due this week',
          ),
        ],
      ),
      RentalProperty(
        id: 'maple-court',
        name: 'Maple Court',
        address: 'Pulchowk Road, Lalitpur',
        totalRooms: 8,
        occupiedRooms: 7,
        monthlyTarget: 9800,
        totalDue: 860,
        rooms: [
          Room(
            id: 'm-301',
            propertyId: 'maple-court',
            label: '301',
            tenantName: 'Marvin McKinney',
            dueDay: 4,
            monthlyRent: 1160,
            status: PaymentStatus.paid,
            note: 'All bills collected',
          ),
          Room(
            id: 'm-302',
            propertyId: 'maple-court',
            label: '302',
            tenantName: 'Kristin Watson',
            dueDay: 7,
            monthlyRent: 1110,
            status: PaymentStatus.partial,
            note: 'Internet pending',
          ),
        ],
      ),
      RentalProperty(
        id: 'riverside-nest',
        name: 'Riverside Nest',
        address: 'Boudha Circle, Kathmandu',
        totalRooms: 10,
        occupiedRooms: 9,
        monthlyTarget: 12100,
        totalDue: 1280,
        rooms: [
          Room(
            id: 'rs-401',
            propertyId: 'riverside-nest',
            label: '401',
            tenantName: 'Savannah Nguyen',
            dueDay: 3,
            monthlyRent: 1235,
            status: PaymentStatus.paid,
            note: 'Paid with electricity',
          ),
          Room(
            id: 'rs-402',
            propertyId: 'riverside-nest',
            label: '402',
            tenantName: 'Devon Lane',
            dueDay: 8,
            monthlyRent: 1185,
            status: PaymentStatus.paid,
            note: 'No dues',
          ),
        ],
      ),
    ],
    revenue: const [
      MonthlyRevenuePoint(month: 'JAN', amount: 34200),
      MonthlyRevenuePoint(month: 'FEB', amount: 36750),
      MonthlyRevenuePoint(month: 'MAR', amount: 35840),
      MonthlyRevenuePoint(month: 'APR', amount: 42850),
      MonthlyRevenuePoint(month: 'MAY', amount: 40120),
      MonthlyRevenuePoint(month: 'JUN', amount: 41780),
    ],
    utilityUsage: const [
      UtilityUsage(
        propertyName: 'Skyline Residences',
        electricity: 2680,
        water: 740,
      ),
      UtilityUsage(
        propertyName: 'Oakwood Apartments',
        electricity: 1710,
        water: 470,
      ),
      UtilityUsage(
        propertyName: 'The Grand Manor',
        electricity: 3920,
        water: 980,
      ),
    ],
    pendingReceivables: const [
      PaymentReceivable(
        id: 'due-suite-401',
        propertyName: 'Emerald Heights',
        roomLabel: 'Suite 401',
        amount: 28500,
        overdueLabel: '14 days overdue',
        tags: ['Rent (2 months)', 'Internet (1 month)', 'Electricity'],
        status: PaymentStatus.due,
      ),
      PaymentReceivable(
        id: 'due-flat-202',
        propertyName: 'Maple Court',
        roomLabel: 'Flat 202',
        amount: 12200,
        overdueLabel: '3 days overdue',
        tags: ['Rent (1 month)', 'Maintenance'],
        status: PaymentStatus.due,
      ),
      PaymentReceivable(
        id: 'due-studio-b',
        propertyName: 'Riverside Nest',
        roomLabel: 'Studio B',
        amount: 3450,
        overdueLabel: 'Since May 01',
        tags: ['Electricity', 'Water Tax'],
        status: PaymentStatus.partial,
      ),
    ],
    completedReceivables: const [
      PaymentReceivable(
        id: 'paid-suite-305',
        propertyName: 'Emerald Heights',
        roomLabel: 'Suite 305',
        amount: 15400,
        overdueLabel: 'Collected on May 12',
        tags: ['Rent', 'Water', 'Internet'],
        status: PaymentStatus.paid,
      ),
      PaymentReceivable(
        id: 'paid-loft-12',
        propertyName: 'Riverside Nest',
        roomLabel: 'Loft 12',
        amount: 11200,
        overdueLabel: 'Collected on May 09',
        tags: ['Rent', 'Electricity'],
        status: PaymentStatus.paid,
      ),
    ],
    preferences: const AppPreferences(
      currencyCode: 'NPR',
      reminderDay: 5,
      landlordName: 'Aarav',
    ),
  );
}
